#!/bin/bash

#
# Base Vars
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
usage() { 
    echo "Usage: $SCRIPT_NAME -f </path/to/config> -n <app name>"
    exit 1
}

#
# Parse cmd line args
#
while getopts "f:n:" opt; do
    case "$opt" in
        f) config=$OPTARG;;
        n) app_name=$OPTARG;;
        *) usage;;
    esac
done
shift $((OPTIND-1))

if [ -z "$config" ] || [ -z "$app_name" ]; then
    usage
fi

#
# Source the config
#
source $config

#
# Main
#
echo -e "\n## Freezing app $app_name"
sudo -u yarn $SLIDER_INST_DIR/bin/slider freeze $app_name --manager $RM_ADDRESS || exit 1
echo "SUCCESS"

echo -e "\n## Destroying app $app_name"
sudo -u yarn $SLIDER_INST_DIR/bin/slider destroy $app_name --manager $RM_ADDRESS || exit 1
echo "SUCCESS"

exit 0
